# Lista de modelos IA gratuitos - exemplo por categoria
# Uso: abra o 9Router e ative os que desejar, OU use via Ollama.
Write-Host "== Modelos IA gratuitos (via 9Router / Ollama) =="
Write-Host ""
Write-Host "[ Nuvem - gratuitos (via 9Router) ]"
Write-Host "  DeepSeek V4 Flash          oc/deepseek-v4-flash-free"
Write-Host "  Mimo V2.5                  oc/mimo-v2.5-free"
Write-Host "  Ling 3.0 Flash             oc/ling-3.0-flash-free"
Write-Host "  Nemotron 3 Ultra           oc/nemotron-3-ultra-free"
Write-Host "  GLM 5.2 (NVIDIA)           nvidia/z-ai/glm-5.2"
Write-Host "  Laguna S 2.1               ps/poolside/laguna-s-2.1"
Write-Host ""
Write-Host "[ Local (Ollama, offline) - escolha conforme sua RAM ]"
Write-Host "  PC basico  (4-8GB)         qwen3:0.6b   ou  llama3.2:1b"
Write-Host "  PC medio   (8-16GB)        qwen3:4b     ou  llama3.2:3b"
Write-Host "  PC bom     (16GB+)         qwen3:8b     ou  llama3.2:8b"
Write-Host "  PC forte   (32GB+)         qwen3:14b"
Write-Host ""
Write-Host "Dica: rode  .\01-install.ps1  para detectar seu hardware e baixar o modelo certo."